AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  IdentityArn:
    Type: String
    Description: SES Identity to send emails from
    
  LambdaUri:
    Type: String
    Description: S3 URI pointing to the ContactLambda function

# Resources:
#   ContactLambda:
#     Type: AWS::Serverless::Function
#     Properties:
#       FunctionName: !Sub ${AWS::StackName}-contact
#       Handler: lambda_function.lambda_handler
#       Runtime: python3.10
#       CodeUri: !Ref LambdaUri
#       Architectures:
#         - x86_64
#       Role: !GetAtt ContactLambdaRole.Arn
  Resources:
    ContactLambda:
      Type: AWS::Lambda::Function
      Properties:
        FunctionName: !Sub ${AWS::StackName}-contact
        Handler: lambda_function.lambda_handler
        Runtime: python3.10
        Code:
          S3Bucket: !Select [0, !Split [/, !Ref LambdaUri]] # Extracts the bucket name
          S3Key: !Select [1, !Split [/, !Ref LambdaUri]] # Extracts the object key
        Architectures:
          - x86_64
        Role: !GetAtt ContactLambdaRole.Arn


  ContactLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-contact
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SESsendemail
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: ses:SendEmail
                Resource: !Ref IdentityArn
