name: Deploy Portfolio Website

on:
  push:
    branches:
      - main

env:
  AWS_ROLE_ARN: arn:aws:iam::767397699663:role/Github-Portfolio-Deploy-OIDC-Role-bne9k9M9ZGEc
  AWS_EXECUTION_ROLE_ARN: arn:aws:iam::767397699663:role/GithubDerpPortfolioDeployExecRole
  AWS_ARTIFACTS_CLOUDFORMATION_URI: s3://derp-portfolio-artifacts/cloudformation
  AWS_ARTIFACTS_LAMBDAS_URI: s3://derp-portfolio-artifacts/lambdas
  TEMPLATE_PATH: CloudFormation/main.yaml
  REGION: us-east-1

jobs:
  upload-artifacts:
    name: Upload templates to S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: us-east-1
      
      - name: Upload templates
        run: |
          aws s3 sync ./CloudFormation ${{ env.AWS_ARTIFACTS_CLOUDFORMATION_URI }}

  deploy:
    name: Deploy Website
    runs-on: ubuntu-latest
    needs: upload-artifacts
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: us-east-1
        
      - name: Upload Lambdas to S3
        run: |
          mkdir lambda-zip
          zip -r lambda-zip/contact-vkaramoutas.zip Lambdas/contact-vkaramoutas

          aws s3 sync ./lambda-zip ${{ env.AWS_ARTIFACTS_LAMBDAS_URI }}

      - name: Deploy SAM template
        run: |
          sam build -t package-prod.yaml
          sam deploy \
          --config-file samconfig.toml \
          --config-env website \
          --role-arn ${{ env.AWS_EXECUTION_ROLE_ARN }}
          --s3-bucket ${{ env.AWS_PACKAGE_URI }}
